---
# tasks file for geekoops-next

# Distribution specific vars are ALWAYS needed, so don't forget the tags here
- name: include distribution specific vars
  include_vars: "{{ansible_distribution}}_{{ansible_distribution_version}}.yml"
  tags: ['dnsmasq']

- name: Ensure dnsmasq is installed
  package:
    name: "{{ packages }}"
    state: present
  tags: ['dnsmasq', 'tftp']
- name: Configure dnsmasq
  template:
    src: dnsmasq.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0755
  notify: restart dnsmasq
  tags: ['dnsmasq', 'tftp']
- name: Ensure pxelinux.cfg is present
  file:
    path: "{{tftp_root}}/pxelinux.cfg"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: ['dnsmasq', 'tftp']
- name: Extract NEXT template
  unarchive:
    src: next.zip
    dest: "{{tftp_root}}/"
    owner: root
    group: root
    mode: 0755
    keep_newer: yes
  tags: ['dnsmasq', 'tftp']
- name: Configure pxelinux.cfg default
  template:
    src: pxelinux_default.j2
    dest: "{{tftp_root}}/pxelinux.cfg/default"
    owner: root
    group: root
    mode: 0755
    force: no
  tags: ['dnsmasq', 'tftp']

- name: Ensure dnsmasq is started and enabled
  systemd:
    name: "{{ dnsmasq_service }}"
    state: started
    enabled: true
  tags: ['dnsmasq', 'tftp']

- include: firewall.yml
  when: config_firewall == true
